### ISSUE TITLE
Typescript in the dependencies

### ISSUE THREAD

**Issue by zdm** [gene-hightower/smtp-address-parser#1]
Could you please remove `typescript` from the `dependencies`, or move it to the `devDependencies`?
It is not required in the production but takes additional 65 Mb, when bundling package to the docker image or electron application.
Thank you.

**Comment by gene-hightower** [comment]
New version 1.0.4, let me know it this works for you.

**Comment by zdm** [comment]
Yes, works.
Thank you very much.
